name: BootCampSample 2020

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12.18.0
   - name: Installing surge
     run:  npm install --global surge
   - name: deploying using surge
     run:  surge ./ bootcamp-piaic.surge.sh --token ${{secrets.SURGE_TOKEN}}
        
